
###


###
## Get Challenges
GET http://localhost:8080/challenge

### Get Invalid Challenge Id
GET http://localhost:8080/challenge/7

### Get Invalid Challenge Id below Min
GET http://localhost:8080/challenge/0

### Get Valid Challenge Id
GET http://localhost:8080/challenge/1

### Get Invalid Challenge Id answer
POST http://localhost:8080/challenge/7/answer

### Get Invalid Challenge Id below Min answer
POST http://localhost:8080/challenge/0/answer

### Provide no answer
POST http://localhost:8080/challenge/1/answer
Content-Type: application/json

### Provide invalid answer
POST http://localhost:8080/challenge/1/answer
Content-Type: application/json

{ "jobId" : 3,
  "answer": "500",
  "email": "john.doe@e.mail",
  "firstName": "string",
  "jobId": 0,
  "lastName": "string",
  "messageToGepardec": "string",
  "otherSource": "string",
  "phone": "string",
  "source": "EMPFEHLUNG",
  "title": "string"
}

### Provide valid answer

POST http://localhost:8080/challenge/1/answer
Content-Type: application/json

{ "jobId" : 3,
  "answer": "50",
  "email": "john.doe@e.mail",
  "firstName": "string",
  "jobId": 0,
  "lastName": "string",
  "messageToGepardec": "string",
  "otherSource": "string",
  "phone": "string",
  "source": "EMPFEHLUNG",
  "title": "string"
}

###